// Code generated by MockGen. DO NOT EDIT.
// Source: iveraisonchallengeresponseclient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	verification "github.com/veraison/apiclient/verification"
)

// MockIVeraisonChallengeResponseClient is a mock of IVeraisonChallengeResponseClient interface.
type MockIVeraisonChallengeResponseClient struct {
	ctrl     *gomock.Controller
	recorder *MockIVeraisonChallengeResponseClientMockRecorder
}

// MockIVeraisonChallengeResponseClientMockRecorder is the mock recorder for MockIVeraisonChallengeResponseClient.
type MockIVeraisonChallengeResponseClientMockRecorder struct {
	mock *MockIVeraisonChallengeResponseClient
}

// NewMockIVeraisonChallengeResponseClient creates a new mock instance.
func NewMockIVeraisonChallengeResponseClient(ctrl *gomock.Controller) *MockIVeraisonChallengeResponseClient {
	mock := &MockIVeraisonChallengeResponseClient{ctrl: ctrl}
	mock.recorder = &MockIVeraisonChallengeResponseClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIVeraisonChallengeResponseClient) EXPECT() *MockIVeraisonChallengeResponseClientMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockIVeraisonChallengeResponseClient) Run() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockIVeraisonChallengeResponseClientMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIVeraisonChallengeResponseClient)(nil).Run))
}

// SetCerts mocks base method.
func (m *MockIVeraisonChallengeResponseClient) SetCerts(paths []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCerts", paths)
}

// SetCerts indicates an expected call of SetCerts.
func (mr *MockIVeraisonChallengeResponseClientMockRecorder) SetCerts(paths interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCerts", reflect.TypeOf((*MockIVeraisonChallengeResponseClient)(nil).SetCerts), paths)
}

// SetDeleteSession mocks base method.
func (m *MockIVeraisonChallengeResponseClient) SetDeleteSession(v bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDeleteSession", v)
}

// SetDeleteSession indicates an expected call of SetDeleteSession.
func (mr *MockIVeraisonChallengeResponseClientMockRecorder) SetDeleteSession(v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDeleteSession", reflect.TypeOf((*MockIVeraisonChallengeResponseClient)(nil).SetDeleteSession), v)
}

// SetEvidenceBuilder mocks base method.
func (m *MockIVeraisonChallengeResponseClient) SetEvidenceBuilder(eb verification.EvidenceBuilder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEvidenceBuilder", eb)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEvidenceBuilder indicates an expected call of SetEvidenceBuilder.
func (mr *MockIVeraisonChallengeResponseClientMockRecorder) SetEvidenceBuilder(eb interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEvidenceBuilder", reflect.TypeOf((*MockIVeraisonChallengeResponseClient)(nil).SetEvidenceBuilder), eb)
}

// SetIsInsecure mocks base method.
func (m *MockIVeraisonChallengeResponseClient) SetIsInsecure(v bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetIsInsecure", v)
}

// SetIsInsecure indicates an expected call of SetIsInsecure.
func (mr *MockIVeraisonChallengeResponseClientMockRecorder) SetIsInsecure(v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIsInsecure", reflect.TypeOf((*MockIVeraisonChallengeResponseClient)(nil).SetIsInsecure), v)
}

// SetNonce mocks base method.
func (m *MockIVeraisonChallengeResponseClient) SetNonce(nonce []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNonce", nonce)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNonce indicates an expected call of SetNonce.
func (mr *MockIVeraisonChallengeResponseClientMockRecorder) SetNonce(nonce interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNonce", reflect.TypeOf((*MockIVeraisonChallengeResponseClient)(nil).SetNonce), nonce)
}

// SetNonceSz mocks base method.
func (m *MockIVeraisonChallengeResponseClient) SetNonceSz(nonceSz uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNonceSz", nonceSz)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNonceSz indicates an expected call of SetNonceSz.
func (mr *MockIVeraisonChallengeResponseClientMockRecorder) SetNonceSz(nonceSz interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNonceSz", reflect.TypeOf((*MockIVeraisonChallengeResponseClient)(nil).SetNonceSz), nonceSz)
}

// SetSessionURI mocks base method.
func (m *MockIVeraisonChallengeResponseClient) SetSessionURI(u string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSessionURI", u)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSessionURI indicates an expected call of SetSessionURI.
func (mr *MockIVeraisonChallengeResponseClientMockRecorder) SetSessionURI(u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionURI", reflect.TypeOf((*MockIVeraisonChallengeResponseClient)(nil).SetSessionURI), u)
}
