// Code generated by MockGen. DO NOT EDIT.
// Source: iveraisondiscoveryclient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	verification "github.com/veraison/apiclient/verification"
)

// MockIVeraisonDiscoveryClient is a mock of IVeraisonDiscoveryClient interface.
type MockIVeraisonDiscoveryClient struct {
	ctrl     *gomock.Controller
	recorder *MockIVeraisonDiscoveryClientMockRecorder
}

// MockIVeraisonDiscoveryClientMockRecorder is the mock recorder for MockIVeraisonDiscoveryClient.
type MockIVeraisonDiscoveryClientMockRecorder struct {
	mock *MockIVeraisonDiscoveryClient
}

// NewMockIVeraisonDiscoveryClient creates a new mock instance.
func NewMockIVeraisonDiscoveryClient(ctrl *gomock.Controller) *MockIVeraisonDiscoveryClient {
	mock := &MockIVeraisonDiscoveryClient{ctrl: ctrl}
	mock.recorder = &MockIVeraisonDiscoveryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIVeraisonDiscoveryClient) EXPECT() *MockIVeraisonDiscoveryClientMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockIVeraisonDiscoveryClient) Run() (*verification.DiscoveryObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(*verification.DiscoveryObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockIVeraisonDiscoveryClientMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIVeraisonDiscoveryClient)(nil).Run))
}

// SetCerts mocks base method.
func (m *MockIVeraisonDiscoveryClient) SetCerts(paths []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCerts", paths)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCerts indicates an expected call of SetCerts.
func (mr *MockIVeraisonDiscoveryClientMockRecorder) SetCerts(paths interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCerts", reflect.TypeOf((*MockIVeraisonDiscoveryClient)(nil).SetCerts), paths)
}

// SetDiscoveryURI mocks base method.
func (m *MockIVeraisonDiscoveryClient) SetDiscoveryURI(u string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDiscoveryURI", u)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDiscoveryURI indicates an expected call of SetDiscoveryURI.
func (mr *MockIVeraisonDiscoveryClientMockRecorder) SetDiscoveryURI(u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDiscoveryURI", reflect.TypeOf((*MockIVeraisonDiscoveryClient)(nil).SetDiscoveryURI), u)
}

// SetIsInsecure mocks base method.
func (m *MockIVeraisonDiscoveryClient) SetIsInsecure() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetIsInsecure")
}

// SetIsInsecure indicates an expected call of SetIsInsecure.
func (mr *MockIVeraisonDiscoveryClientMockRecorder) SetIsInsecure() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIsInsecure", reflect.TypeOf((*MockIVeraisonDiscoveryClient)(nil).SetIsInsecure))
}
