# Copyright 2021-2022 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

SUBDIR := common
SUBDIR += scheme-tcg-dice
SUBDIR += scheme-psa-iot
SUBDIR += scheme-tpm-enacttrust

include ../../mk/subdir.mk
