# Copyright 2023-2026 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

PLUGIN := ../../bin/scheme-parsec-cca.plugin
GOPKG := github.com/veraison/services/scheme/parsec-cca
SRCS := main.go

include ../../../mk/common.mk
include ../../../mk/plugin.mk
include ../../../mk/lint.mk
include ../../../mk/test.mk
