// Code generated by MockGen. DO NOT EDIT.
// Source: ../provisioner/iprovisioner.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	proto "github.com/veraison/services/proto"
)

// MockIProvisioner is a mock of IProvisioner interface.
type MockIProvisioner struct {
	ctrl     *gomock.Controller
	recorder *MockIProvisionerMockRecorder
}

// MockIProvisionerMockRecorder is the mock recorder for MockIProvisioner.
type MockIProvisionerMockRecorder struct {
	mock *MockIProvisioner
}

// NewMockIProvisioner creates a new mock instance.
func NewMockIProvisioner(ctrl *gomock.Controller) *MockIProvisioner {
	mock := &MockIProvisioner{ctrl: ctrl}
	mock.recorder = &MockIProvisionerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProvisioner) EXPECT() *MockIProvisionerMockRecorder {
	return m.recorder
}

// GetVTSState mocks base method.
func (m *MockIProvisioner) GetVTSState() (*proto.ServiceState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVTSState")
	ret0, _ := ret[0].(*proto.ServiceState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVTSState indicates an expected call of GetVTSState.
func (mr *MockIProvisionerMockRecorder) GetVTSState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVTSState", reflect.TypeOf((*MockIProvisioner)(nil).GetVTSState))
}

// IsSupportedMediaType mocks base method.
func (m *MockIProvisioner) IsSupportedMediaType(mt string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSupportedMediaType", mt)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSupportedMediaType indicates an expected call of IsSupportedMediaType.
func (mr *MockIProvisionerMockRecorder) IsSupportedMediaType(mt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSupportedMediaType", reflect.TypeOf((*MockIProvisioner)(nil).IsSupportedMediaType), mt)
}

// SubmitEndorsements mocks base method.
func (m *MockIProvisioner) SubmitEndorsements(tenantID string, data []byte, mt string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitEndorsements", tenantID, data, mt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitEndorsements indicates an expected call of SubmitEndorsements.
func (mr *MockIProvisionerMockRecorder) SubmitEndorsements(tenantID, data, mt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitEndorsements", reflect.TypeOf((*MockIProvisioner)(nil).SubmitEndorsements), tenantID, data, mt)
}

// SupportedMediaTypes mocks base method.
func (m *MockIProvisioner) SupportedMediaTypes() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportedMediaTypes")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SupportedMediaTypes indicates an expected call of SupportedMediaTypes.
func (mr *MockIProvisionerMockRecorder) SupportedMediaTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportedMediaTypes", reflect.TypeOf((*MockIProvisioner)(nil).SupportedMediaTypes))
}
