// Code generated by MockGen. DO NOT EDIT.
// Source: ../../trustedservices/itrustedservices.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	proto "github.com/veraison/services/proto"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockITrustedServices is a mock of ITrustedServices interface.
type MockITrustedServices struct {
	ctrl     *gomock.Controller
	recorder *MockITrustedServicesMockRecorder
}

// MockITrustedServicesMockRecorder is the mock recorder for MockITrustedServices.
type MockITrustedServicesMockRecorder struct {
	mock *MockITrustedServices
}

// NewMockITrustedServices creates a new mock instance.
func NewMockITrustedServices(ctrl *gomock.Controller) *MockITrustedServices {
	mock := &MockITrustedServices{ctrl: ctrl}
	mock.recorder = &MockITrustedServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITrustedServices) EXPECT() *MockITrustedServicesMockRecorder {
	return m.recorder
}

// AddRefValues mocks base method.
func (m *MockITrustedServices) AddRefValues(ctx context.Context, in *proto.AddRefValuesRequest, opts ...grpc.CallOption) (*proto.AddRefValuesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddRefValues", varargs...)
	ret0, _ := ret[0].(*proto.AddRefValuesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRefValues indicates an expected call of AddRefValues.
func (mr *MockITrustedServicesMockRecorder) AddRefValues(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRefValues", reflect.TypeOf((*MockITrustedServices)(nil).AddRefValues), varargs...)
}

// AddTrustAnchor mocks base method.
func (m *MockITrustedServices) AddTrustAnchor(ctx context.Context, in *proto.AddTrustAnchorRequest, opts ...grpc.CallOption) (*proto.AddTrustAnchorResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddTrustAnchor", varargs...)
	ret0, _ := ret[0].(*proto.AddTrustAnchorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTrustAnchor indicates an expected call of AddTrustAnchor.
func (mr *MockITrustedServicesMockRecorder) AddTrustAnchor(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTrustAnchor", reflect.TypeOf((*MockITrustedServices)(nil).AddTrustAnchor), varargs...)
}

// GetAttestation mocks base method.
func (m *MockITrustedServices) GetAttestation(ctx context.Context, in *proto.AttestationToken, opts ...grpc.CallOption) (*proto.AppraisalContext, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAttestation", varargs...)
	ret0, _ := ret[0].(*proto.AppraisalContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttestation indicates an expected call of GetAttestation.
func (mr *MockITrustedServicesMockRecorder) GetAttestation(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttestation", reflect.TypeOf((*MockITrustedServices)(nil).GetAttestation), varargs...)
}

// GetServiceState mocks base method.
func (m *MockITrustedServices) GetServiceState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*proto.ServiceState, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetServiceState", varargs...)
	ret0, _ := ret[0].(*proto.ServiceState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceState indicates an expected call of GetServiceState.
func (mr *MockITrustedServicesMockRecorder) GetServiceState(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceState", reflect.TypeOf((*MockITrustedServices)(nil).GetServiceState), varargs...)
}

// GetSupportedVerificationMediaTypes mocks base method.
func (m *MockITrustedServices) GetSupportedVerificationMediaTypes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*proto.MediaTypeList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSupportedVerificationMediaTypes", varargs...)
	ret0, _ := ret[0].(*proto.MediaTypeList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupportedVerificationMediaTypes indicates an expected call of GetSupportedVerificationMediaTypes.
func (mr *MockITrustedServicesMockRecorder) GetSupportedVerificationMediaTypes(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportedVerificationMediaTypes", reflect.TypeOf((*MockITrustedServices)(nil).GetSupportedVerificationMediaTypes), varargs...)
}
