# Copyright 2022 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

PLUGIN := ../bin/trooper.plugin
GOPKG := github.com/veraison/services/plugin/test/trooper
SRCS := trooper.go

include ../../../mk/common.mk
include ../../../mk/plugin.mk
