# Copyright 2022 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

PLUGIN := ../bin/scheme-tpm-parsec
GOPKG := github.com/veraison/services/vts/plugins/scheme-tpm-parsec
SRCS := main.go

#test-hook-pre:
#	$(MAKE) -C test/

SUBDIR := test

include ../../../mk/common.mk
include ../../../mk/plugin.mk
include ../../../mk/lint.mk
include ../../../mk/test.mk
include ../../../mk/subdir.mk
