// Code generated by MockGen. DO NOT EDIT.
// Source: ../../handler/iendorsementstore.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	comid "github.com/veraison/corim/comid"
	coserv "github.com/veraison/corim/coserv"
	plugin "github.com/veraison/services/plugin"
)

// MockIEndorsementStorePlugin is a mock of IEndorsementStorePlugin interface.
type MockIEndorsementStorePlugin struct {
	ctrl     *gomock.Controller
	recorder *MockIEndorsementStorePluginMockRecorder
}

// MockIEndorsementStorePluginMockRecorder is the mock recorder for MockIEndorsementStorePlugin.
type MockIEndorsementStorePluginMockRecorder struct {
	mock *MockIEndorsementStorePlugin
}

// NewMockIEndorsementStorePlugin creates a new mock instance.
func NewMockIEndorsementStorePlugin(ctrl *gomock.Controller) *MockIEndorsementStorePlugin {
	mock := &MockIEndorsementStorePlugin{ctrl: ctrl}
	mock.recorder = &MockIEndorsementStorePluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEndorsementStorePlugin) EXPECT() *MockIEndorsementStorePluginMockRecorder {
	return m.recorder
}

// AddCorimBytes mocks base method.
func (m *MockIEndorsementStorePlugin) AddCorimBytes(data []byte, scheme string, activate bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCorimBytes", data, scheme, activate)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCorimBytes indicates an expected call of AddCorimBytes.
func (mr *MockIEndorsementStorePluginMockRecorder) AddCorimBytes(data, scheme, activate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCorimBytes", reflect.TypeOf((*MockIEndorsementStorePlugin)(nil).AddCorimBytes), data, scheme, activate)
}

// ExecuteCoservQuery mocks base method.
func (m *MockIEndorsementStorePlugin) ExecuteCoservQuery(profile, query string) (*coserv.Coserv, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteCoservQuery", profile, query)
	ret0, _ := ret[0].(*coserv.Coserv)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteCoservQuery indicates an expected call of ExecuteCoservQuery.
func (mr *MockIEndorsementStorePluginMockRecorder) ExecuteCoservQuery(profile, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteCoservQuery", reflect.TypeOf((*MockIEndorsementStorePlugin)(nil).ExecuteCoservQuery), profile, query)
}

// Fini mocks base method.
func (m *MockIEndorsementStorePlugin) Fini() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fini")
	ret0, _ := ret[0].(error)
	return ret0
}

// Fini indicates an expected call of Fini.
func (mr *MockIEndorsementStorePluginMockRecorder) Fini() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fini", reflect.TypeOf((*MockIEndorsementStorePlugin)(nil).Fini))
}

// GetAttestationScheme mocks base method.
func (m *MockIEndorsementStorePlugin) GetAttestationScheme() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttestationScheme")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAttestationScheme indicates an expected call of GetAttestationScheme.
func (mr *MockIEndorsementStorePluginMockRecorder) GetAttestationScheme() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttestationScheme", reflect.TypeOf((*MockIEndorsementStorePlugin)(nil).GetAttestationScheme))
}

// GetKeyTriples mocks base method.
func (m *MockIEndorsementStorePlugin) GetKeyTriples(env *comid.Environment, scheme string, exact bool) ([]*comid.KeyTriple, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyTriples", env, scheme, exact)
	ret0, _ := ret[0].([]*comid.KeyTriple)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyTriples indicates an expected call of GetKeyTriples.
func (mr *MockIEndorsementStorePluginMockRecorder) GetKeyTriples(env, scheme, exact interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyTriples", reflect.TypeOf((*MockIEndorsementStorePlugin)(nil).GetKeyTriples), env, scheme, exact)
}

// GetName mocks base method.
func (m *MockIEndorsementStorePlugin) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockIEndorsementStorePluginMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockIEndorsementStorePlugin)(nil).GetName))
}

// GetSupportedMediaTypes mocks base method.
func (m *MockIEndorsementStorePlugin) GetSupportedMediaTypes() map[string][]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupportedMediaTypes")
	ret0, _ := ret[0].(map[string][]string)
	return ret0
}

// GetSupportedMediaTypes indicates an expected call of GetSupportedMediaTypes.
func (mr *MockIEndorsementStorePluginMockRecorder) GetSupportedMediaTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportedMediaTypes", reflect.TypeOf((*MockIEndorsementStorePlugin)(nil).GetSupportedMediaTypes))
}

// GetValueTriples mocks base method.
func (m *MockIEndorsementStorePlugin) GetValueTriples(env *comid.Environment, scheme string, exact bool) ([]*comid.ValueTriple, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValueTriples", env, scheme, exact)
	ret0, _ := ret[0].([]*comid.ValueTriple)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValueTriples indicates an expected call of GetValueTriples.
func (mr *MockIEndorsementStorePluginMockRecorder) GetValueTriples(env, scheme, exact interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValueTriples", reflect.TypeOf((*MockIEndorsementStorePlugin)(nil).GetValueTriples), env, scheme, exact)
}

// Init mocks base method.
func (m *MockIEndorsementStorePlugin) Init(params *plugin.Parameters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockIEndorsementStorePluginMockRecorder) Init(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockIEndorsementStorePlugin)(nil).Init), params)
}

// MockIEndorsementStore is a mock of IEndorsementStore interface.
type MockIEndorsementStore struct {
	ctrl     *gomock.Controller
	recorder *MockIEndorsementStoreMockRecorder
}

// MockIEndorsementStoreMockRecorder is the mock recorder for MockIEndorsementStore.
type MockIEndorsementStoreMockRecorder struct {
	mock *MockIEndorsementStore
}

// NewMockIEndorsementStore creates a new mock instance.
func NewMockIEndorsementStore(ctrl *gomock.Controller) *MockIEndorsementStore {
	mock := &MockIEndorsementStore{ctrl: ctrl}
	mock.recorder = &MockIEndorsementStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEndorsementStore) EXPECT() *MockIEndorsementStoreMockRecorder {
	return m.recorder
}

// AddCorimBytes mocks base method.
func (m *MockIEndorsementStore) AddCorimBytes(data []byte, scheme string, activate bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCorimBytes", data, scheme, activate)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCorimBytes indicates an expected call of AddCorimBytes.
func (mr *MockIEndorsementStoreMockRecorder) AddCorimBytes(data, scheme, activate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCorimBytes", reflect.TypeOf((*MockIEndorsementStore)(nil).AddCorimBytes), data, scheme, activate)
}

// ExecuteCoservQuery mocks base method.
func (m *MockIEndorsementStore) ExecuteCoservQuery(profile, query string) (*coserv.Coserv, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteCoservQuery", profile, query)
	ret0, _ := ret[0].(*coserv.Coserv)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteCoservQuery indicates an expected call of ExecuteCoservQuery.
func (mr *MockIEndorsementStoreMockRecorder) ExecuteCoservQuery(profile, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteCoservQuery", reflect.TypeOf((*MockIEndorsementStore)(nil).ExecuteCoservQuery), profile, query)
}

// GetKeyTriples mocks base method.
func (m *MockIEndorsementStore) GetKeyTriples(env *comid.Environment, scheme string, exact bool) ([]*comid.KeyTriple, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyTriples", env, scheme, exact)
	ret0, _ := ret[0].([]*comid.KeyTriple)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyTriples indicates an expected call of GetKeyTriples.
func (mr *MockIEndorsementStoreMockRecorder) GetKeyTriples(env, scheme, exact interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyTriples", reflect.TypeOf((*MockIEndorsementStore)(nil).GetKeyTriples), env, scheme, exact)
}

// GetValueTriples mocks base method.
func (m *MockIEndorsementStore) GetValueTriples(env *comid.Environment, scheme string, exact bool) ([]*comid.ValueTriple, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValueTriples", env, scheme, exact)
	ret0, _ := ret[0].([]*comid.ValueTriple)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValueTriples indicates an expected call of GetValueTriples.
func (mr *MockIEndorsementStoreMockRecorder) GetValueTriples(env, scheme, exact interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValueTriples", reflect.TypeOf((*MockIEndorsementStore)(nil).GetValueTriples), env, scheme, exact)
}
