# Copyright 2025 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

ifndef COMBINED_PLUGINS
  SUBDIR += endorsement-handler
  SUBDIR += evidence-handler
  SUBDIR += store-handler
else
  SUBDIR += combined
endif

include ../../../mk/common.mk
include ../../../mk/subdir.mk
