# Copyright 2024 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

GOPKG := github.com/veraison/services/scheme/common/arm

SRCS := $(wildcard *.go)

SUBDIR += cca
SUBDIR += psa
SUBDIR += platform

include ../../../mk/common.mk
include ../../../mk/lint.mk
include ../../../mk/pkg.mk
include ../../../mk/test.mk
