# Copyright <TODO> Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

PLUGIN := ../../bin/scheme-<TODO>.plugin
GOPKG := github.com/veraison/services/scheme/<TODO>
SRCS := main.go

include ../../../mk/common.mk
include ../../../mk/plugin.mk
include ../../../mk/lint.mk
include ../../../mk/test.mk
