# Copyright 2022 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

SUBDIR := plugins
SUBDIR += trustedservices
SUBDIR += pluginmanager
SUBDIR += cmd

include ../mk/subdir.mk
