# Copyright 2021 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

PLUGIN := ../bin/scheme-aws-nitro
GOPKG := github.com/veraison/services/vts/plugins/scheme-aws-nitro
SRCS := main.go

include ../../../mk/common.mk
include ../../../mk/plugin.mk
include ../../../mk/lint.mk
include ../../../mk/test.mk