# Copyright 2022 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

PLUGIN := ../../bin/scheme-tpm-enacttrust.plugin
GOPKG := github.com/veraison/services/scheme/tpm-enacttrust
SRCS := main.go

include ../../../mk/common.mk
include ../../../mk/plugin.mk
include ../../../mk/lint.mk
include ../../../mk/test.mk
