# Copyright 2026 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

INTERFACES := ../../handler/iendorsementstore.go

MOCKPKG := mocks

lint-hook-pre: _mocks

include ../../mk/common.mk
include ../../mk/pkg.mk
include ../../mk/lint.mk
include ../../mk/test.mk
