plugin:
  backend: builtin
po-store:
  backend: sql
  sql:
    driver: sqlite3
    datasource: /veraison/stores/vts/po-store.sql
management:
  listen-addr: 0.0.0.0:8088
  protocol: https
  cert: ../../../deployments/docker/src/certs/management.crt
  cert-key: ../../../deployments/docker/src/certs/management.key
po-agent:
  backend: opa
logging:
  level: debug
auth:
  backend: keycloak
  host: keycloak-service
  port: 11111
  realm: veraison
