// Code generated by MockGen. DO NOT EDIT.
// Source: ../earsigner/iearsigner.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	jwa "github.com/lestrrat-go/jwx/v2/jwa"
	jwk "github.com/lestrrat-go/jwx/v2/jwk"
	ear "github.com/veraison/ear"
	earsigner "github.com/veraison/services/vts/earsigner"
)

// MockIEarSigner is a mock of IEarSigner interface.
type MockIEarSigner struct {
	ctrl     *gomock.Controller
	recorder *MockIEarSignerMockRecorder
}

// MockIEarSignerMockRecorder is the mock recorder for MockIEarSigner.
type MockIEarSignerMockRecorder struct {
	mock *MockIEarSigner
}

// NewMockIEarSigner creates a new mock instance.
func NewMockIEarSigner(ctrl *gomock.Controller) *MockIEarSigner {
	mock := &MockIEarSigner{ctrl: ctrl}
	mock.recorder = &MockIEarSignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEarSigner) EXPECT() *MockIEarSignerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockIEarSigner) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIEarSignerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIEarSigner)(nil).Close))
}

// GetEARSigningPublicKey mocks base method.
func (m *MockIEarSigner) GetEARSigningPublicKey() (jwa.KeyAlgorithm, jwk.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEARSigningPublicKey")
	ret0, _ := ret[0].(jwa.KeyAlgorithm)
	ret1, _ := ret[1].(jwk.Key)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetEARSigningPublicKey indicates an expected call of GetEARSigningPublicKey.
func (mr *MockIEarSignerMockRecorder) GetEARSigningPublicKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEARSigningPublicKey", reflect.TypeOf((*MockIEarSigner)(nil).GetEARSigningPublicKey))
}

// Init mocks base method.
func (m *MockIEarSigner) Init(cfg earsigner.Cfg, key []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", cfg, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockIEarSignerMockRecorder) Init(cfg, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockIEarSigner)(nil).Init), cfg, key)
}

// Sign mocks base method.
func (m *MockIEarSigner) Sign(earClaims ear.AttestationResult) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sign", earClaims)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sign indicates an expected call of Sign.
func (mr *MockIEarSignerMockRecorder) Sign(earClaims interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*MockIEarSigner)(nil).Sign), earClaims)
}
