// Code generated by MockGen. DO NOT EDIT.
// Source: ../../handler/ievidencehandler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ear "github.com/veraison/ear"
	proto "github.com/veraison/services/proto"
)

// MockIEvidenceHandler is a mock of IEvidenceHandler interface.
type MockIEvidenceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIEvidenceHandlerMockRecorder
}

// MockIEvidenceHandlerMockRecorder is the mock recorder for MockIEvidenceHandler.
type MockIEvidenceHandlerMockRecorder struct {
	mock *MockIEvidenceHandler
}

// NewMockIEvidenceHandler creates a new mock instance.
func NewMockIEvidenceHandler(ctrl *gomock.Controller) *MockIEvidenceHandler {
	mock := &MockIEvidenceHandler{ctrl: ctrl}
	mock.recorder = &MockIEvidenceHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEvidenceHandler) EXPECT() *MockIEvidenceHandlerMockRecorder {
	return m.recorder
}

// AppraiseEvidence mocks base method.
func (m *MockIEvidenceHandler) AppraiseEvidence(ec *proto.EvidenceContext, endorsements []string) (*ear.AttestationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppraiseEvidence", ec, endorsements)
	ret0, _ := ret[0].(*ear.AttestationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppraiseEvidence indicates an expected call of AppraiseEvidence.
func (mr *MockIEvidenceHandlerMockRecorder) AppraiseEvidence(ec, endorsements interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppraiseEvidence", reflect.TypeOf((*MockIEvidenceHandler)(nil).AppraiseEvidence), ec, endorsements)
}

// ExtractClaims mocks base method.
func (m *MockIEvidenceHandler) ExtractClaims(token *proto.AttestationToken, trustAnchors []string) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractClaims", token, trustAnchors)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractClaims indicates an expected call of ExtractClaims.
func (mr *MockIEvidenceHandlerMockRecorder) ExtractClaims(token, trustAnchors interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractClaims", reflect.TypeOf((*MockIEvidenceHandler)(nil).ExtractClaims), token, trustAnchors)
}

// GetAttestationScheme mocks base method.
func (m *MockIEvidenceHandler) GetAttestationScheme() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttestationScheme")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAttestationScheme indicates an expected call of GetAttestationScheme.
func (mr *MockIEvidenceHandlerMockRecorder) GetAttestationScheme() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttestationScheme", reflect.TypeOf((*MockIEvidenceHandler)(nil).GetAttestationScheme))
}

// GetName mocks base method.
func (m *MockIEvidenceHandler) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockIEvidenceHandlerMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockIEvidenceHandler)(nil).GetName))
}

// GetSupportedMediaTypes mocks base method.
func (m *MockIEvidenceHandler) GetSupportedMediaTypes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupportedMediaTypes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSupportedMediaTypes indicates an expected call of GetSupportedMediaTypes.
func (mr *MockIEvidenceHandlerMockRecorder) GetSupportedMediaTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportedMediaTypes", reflect.TypeOf((*MockIEvidenceHandler)(nil).GetSupportedMediaTypes))
}

// ValidateEvidenceIntegrity mocks base method.
func (m *MockIEvidenceHandler) ValidateEvidenceIntegrity(token *proto.AttestationToken, trustAnchors, endorsementsStrings []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateEvidenceIntegrity", token, trustAnchors, endorsementsStrings)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateEvidenceIntegrity indicates an expected call of ValidateEvidenceIntegrity.
func (mr *MockIEvidenceHandlerMockRecorder) ValidateEvidenceIntegrity(token, trustAnchors, endorsementsStrings interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateEvidenceIntegrity", reflect.TypeOf((*MockIEvidenceHandler)(nil).ValidateEvidenceIntegrity), token, trustAnchors, endorsementsStrings)
}
