// Code generated by MockGen. DO NOT EDIT.
// Source: ../../plugin/ipluggable.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIPluggable is a mock of IPluggable interface.
type MockIPluggable struct {
	ctrl     *gomock.Controller
	recorder *MockIPluggableMockRecorder
}

// MockIPluggableMockRecorder is the mock recorder for MockIPluggable.
type MockIPluggableMockRecorder struct {
	mock *MockIPluggable
}

// NewMockIPluggable creates a new mock instance.
func NewMockIPluggable(ctrl *gomock.Controller) *MockIPluggable {
	mock := &MockIPluggable{ctrl: ctrl}
	mock.recorder = &MockIPluggableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPluggable) EXPECT() *MockIPluggableMockRecorder {
	return m.recorder
}

// GetAttestationScheme mocks base method.
func (m *MockIPluggable) GetAttestationScheme() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttestationScheme")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAttestationScheme indicates an expected call of GetAttestationScheme.
func (mr *MockIPluggableMockRecorder) GetAttestationScheme() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttestationScheme", reflect.TypeOf((*MockIPluggable)(nil).GetAttestationScheme))
}

// GetName mocks base method.
func (m *MockIPluggable) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockIPluggableMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockIPluggable)(nil).GetName))
}

// GetSupportedMediaTypes mocks base method.
func (m *MockIPluggable) GetSupportedMediaTypes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupportedMediaTypes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSupportedMediaTypes indicates an expected call of GetSupportedMediaTypes.
func (mr *MockIPluggableMockRecorder) GetSupportedMediaTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportedMediaTypes", reflect.TypeOf((*MockIPluggable)(nil).GetSupportedMediaTypes))
}
