// Code generated by MockGen. DO NOT EDIT.
// Source: ../policymanager/ipolicymanager.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	appraisal "github.com/veraison/services/vts/appraisal"
)

// MockIPolicyManager is a mock of IPolicyManager interface.
type MockIPolicyManager struct {
	ctrl     *gomock.Controller
	recorder *MockIPolicyManagerMockRecorder
}

// MockIPolicyManagerMockRecorder is the mock recorder for MockIPolicyManager.
type MockIPolicyManagerMockRecorder struct {
	mock *MockIPolicyManager
}

// NewMockIPolicyManager creates a new mock instance.
func NewMockIPolicyManager(ctrl *gomock.Controller) *MockIPolicyManager {
	mock := &MockIPolicyManager{ctrl: ctrl}
	mock.recorder = &MockIPolicyManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPolicyManager) EXPECT() *MockIPolicyManagerMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockIPolicyManager) Evaluate(ctx context.Context, appraisal *appraisal.Appraisal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", ctx, appraisal)
	ret0, _ := ret[0].(error)
	return ret0
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockIPolicyManagerMockRecorder) Evaluate(ctx, appraisal interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockIPolicyManager)(nil).Evaluate), ctx, appraisal)
}
