// Code generated by MockGen. DO NOT EDIT.
// Source: ../../handler/istorehandler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	handler "github.com/veraison/services/handler"
	proto "github.com/veraison/services/proto"
)

// MockIStoreHandler is a mock of IStoreHandler interface.
type MockIStoreHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIStoreHandlerMockRecorder
}

// MockIStoreHandlerMockRecorder is the mock recorder for MockIStoreHandler.
type MockIStoreHandlerMockRecorder struct {
	mock *MockIStoreHandler
}

// NewMockIStoreHandler creates a new mock instance.
func NewMockIStoreHandler(ctrl *gomock.Controller) *MockIStoreHandler {
	mock := &MockIStoreHandler{ctrl: ctrl}
	mock.recorder = &MockIStoreHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStoreHandler) EXPECT() *MockIStoreHandlerMockRecorder {
	return m.recorder
}

// GetAttestationScheme mocks base method.
func (m *MockIStoreHandler) GetAttestationScheme() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttestationScheme")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAttestationScheme indicates an expected call of GetAttestationScheme.
func (mr *MockIStoreHandlerMockRecorder) GetAttestationScheme() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttestationScheme", reflect.TypeOf((*MockIStoreHandler)(nil).GetAttestationScheme))
}

// GetName mocks base method.
func (m *MockIStoreHandler) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockIStoreHandlerMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockIStoreHandler)(nil).GetName))
}

// GetRefValueIDs mocks base method.
func (m *MockIStoreHandler) GetRefValueIDs(tenantID string, trustAnchors []string, claims map[string]interface{}) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefValueIDs", tenantID, trustAnchors, claims)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefValueIDs indicates an expected call of GetRefValueIDs.
func (mr *MockIStoreHandlerMockRecorder) GetRefValueIDs(tenantID, trustAnchors, claims interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefValueIDs", reflect.TypeOf((*MockIStoreHandler)(nil).GetRefValueIDs), tenantID, trustAnchors, claims)
}

// GetSupportedMediaTypes mocks base method.
func (m *MockIStoreHandler) GetSupportedMediaTypes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupportedMediaTypes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSupportedMediaTypes indicates an expected call of GetSupportedMediaTypes.
func (mr *MockIStoreHandlerMockRecorder) GetSupportedMediaTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportedMediaTypes", reflect.TypeOf((*MockIStoreHandler)(nil).GetSupportedMediaTypes))
}

// GetTrustAnchorIDs mocks base method.
func (m *MockIStoreHandler) GetTrustAnchorIDs(token *proto.AttestationToken) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrustAnchorIDs", token)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrustAnchorIDs indicates an expected call of GetTrustAnchorIDs.
func (mr *MockIStoreHandlerMockRecorder) GetTrustAnchorIDs(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrustAnchorIDs", reflect.TypeOf((*MockIStoreHandler)(nil).GetTrustAnchorIDs), token)
}

// SynthCoservQueryKeys mocks base method.
func (m *MockIStoreHandler) SynthCoservQueryKeys(tenantID, query string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SynthCoservQueryKeys", tenantID, query)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SynthCoservQueryKeys indicates an expected call of SynthCoservQueryKeys.
func (mr *MockIStoreHandlerMockRecorder) SynthCoservQueryKeys(tenantID, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SynthCoservQueryKeys", reflect.TypeOf((*MockIStoreHandler)(nil).SynthCoservQueryKeys), tenantID, query)
}

// SynthKeysFromRefValue mocks base method.
func (m *MockIStoreHandler) SynthKeysFromRefValue(tenantID string, refVal *handler.Endorsement) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SynthKeysFromRefValue", tenantID, refVal)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SynthKeysFromRefValue indicates an expected call of SynthKeysFromRefValue.
func (mr *MockIStoreHandlerMockRecorder) SynthKeysFromRefValue(tenantID, refVal interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SynthKeysFromRefValue", reflect.TypeOf((*MockIStoreHandler)(nil).SynthKeysFromRefValue), tenantID, refVal)
}

// SynthKeysFromTrustAnchor mocks base method.
func (m *MockIStoreHandler) SynthKeysFromTrustAnchor(tenantID string, ta *handler.Endorsement) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SynthKeysFromTrustAnchor", tenantID, ta)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SynthKeysFromTrustAnchor indicates an expected call of SynthKeysFromTrustAnchor.
func (mr *MockIStoreHandlerMockRecorder) SynthKeysFromTrustAnchor(tenantID, ta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SynthKeysFromTrustAnchor", reflect.TypeOf((*MockIStoreHandler)(nil).SynthKeysFromTrustAnchor), tenantID, ta)
}
