# Copyright 2026 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

PLUGIN := ../../bin/scheme-da-spdm.plugin
GOPKG := github.com/veraison/services/scheme/da-spdm
SRCS := main.go

include ../../../mk/common.mk
include ../../../mk/plugin.mk
include ../../../mk/lint.mk

test:
