#!/bin/bash
# Copyright 2023 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0
THIS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

VERAISON=veraison
RUN_LOADS=$THIS_DIR/scripts/run-loads.py
EXTRACT_GIN_LOGS=$THIS_DIR/scripts/extract-gin-logs

function do_runs() {
    local service=$1
    local num_steps=$2
    local step=$3
    local duration=$4
    local outdir=$5

    if [[ ! -d $outdir ]]; then
        mkdir -p $outdir
    fi

    ulimit -n 10000

    set -e

    for i in $(seq 1 $num_steps); do
        local basename="status-u$[$i*$step]-d$duration"

        $VERAISON clear-logs
        $RUN_LOADS --service $service  --users $[$i*$step] --duration $duration \
		--outfile $outdir/$basename.json
        $VERAISON logs $outdir/$basename-logs
        $EXTRACT_GIN_LOGS $outdir/$basename-logs/provisioning-stdout.log \
                          $outdir/$basename-prov.csv \
                          $outdir/errors.csv
        $EXTRACT_GIN_LOGS $outdir/$basename-logs/verification-stdout.log \
                          $outdir/$basename-verif.csv \
                          $outdir/errors.csv
    done

    set +e
}

if [[ $# != 5 ]]; then
    echo "Usage: service do-runs NUM_STEPS STEP DURATION OUTPUT_DIR"
    exit 1
fi

do_runs $1 $2 $3 $4 $5
