#!/bin/bash
THIS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

VERAISON=$THIS_DIR/../deployments/docker/veraison
RUN_LOADS=$THIS_DIR/scripts/run-loads.py
EXTRACT_GIN_LOGS=$THIS_DIR/scripts/extract-gin-logs

function do_runs() {
    local num_steps=$1
    local step=$2
    local duration=$3
    local outdir=$4

    if [[ ! -d $outdir ]]; then
        mkdir -p $outdir
    fi

    ulimit -n 10000

    set -e

    for i in $(seq 1 $num_steps); do
        local basename="status-u$[$i*$step]-d$duration"

        $VERAISON clear-logs
        $RUN_LOADS  --users $[$i*$step] --duration $duration --outfile $outdir/$basename.json
        $VERAISON logs $outdir/$basename-logs
        $EXTRACT_GIN_LOGS $outdir/$basename-logs/provisioning-stdout.log \
                          $outdir/$basename-prov.csv \
                          $outdir/errors.csv
        $EXTRACT_GIN_LOGS $outdir/$basename-logs/verification-stdout.log \
                          $outdir/$basename-verif.csv \
                          $outdir/errors.csv
    done

    set +e
}

if [[ $# != 4 ]]; then
    echo "Usage: do-runs NUM_STEPS STEP DURATION OUTPUT_DIR"
    exit 1
fi

do_runs $1 $2 $3 $4
