# Copyright 2021 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

PLUGIN := ../bin/scheme-cca-ssd-platform
GOPKG := github.com/veraison/services/vts/plugins/scheme-cca-ssd-platform
SRCS := main.go

include ../../../mk/common.mk
include ../../../mk/plugin.mk
include ../../../mk/lint.mk
include ../../../mk/test.mk
