# Copyright 2022-2026 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

include ../../mk/common.mk
include ../../mk/lint.mk
include ../../mk/pkg.mk
include ../../mk/test.mk
