
ifndef COMBINED_PLUGINS
  SUBDIR += endorsement-handler
  SUBDIR += evidence-handler
  SUBDIR += store-handler
else
  SUBDIR += combined
endif

include ../../../mk/common.mk
include ../../../mk/subdir.mk
