// Copyright 2025 Contributors to the Veraison project.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: endorsement_query.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndorsementQueryIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// media type (including profile)
	MediaType string `protobuf:"bytes,1,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	// base64url-encoded CoSERV
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *EndorsementQueryIn) Reset() {
	*x = EndorsementQueryIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endorsement_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndorsementQueryIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndorsementQueryIn) ProtoMessage() {}

func (x *EndorsementQueryIn) ProtoReflect() protoreflect.Message {
	mi := &file_endorsement_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndorsementQueryIn.ProtoReflect.Descriptor instead.
func (*EndorsementQueryIn) Descriptor() ([]byte, []int) {
	return file_endorsement_query_proto_rawDescGZIP(), []int{0}
}

func (x *EndorsementQueryIn) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *EndorsementQueryIn) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type EndorsementQueryOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ResultSet []byte  `protobuf:"bytes,2,opt,name=result_set,json=resultSet,proto3" json:"result_set,omitempty"`
}

func (x *EndorsementQueryOut) Reset() {
	*x = EndorsementQueryOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endorsement_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndorsementQueryOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndorsementQueryOut) ProtoMessage() {}

func (x *EndorsementQueryOut) ProtoReflect() protoreflect.Message {
	mi := &file_endorsement_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndorsementQueryOut.ProtoReflect.Descriptor instead.
func (*EndorsementQueryOut) Descriptor() ([]byte, []int) {
	return file_endorsement_query_proto_rawDescGZIP(), []int{1}
}

func (x *EndorsementQueryOut) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *EndorsementQueryOut) GetResultSet() []byte {
	if x != nil {
		return x.ResultSet
	}
	return nil
}

var File_endorsement_query_proto protoreflect.FileDescriptor

var file_endorsement_query_proto_rawDesc = []byte{
	0x0a, 0x17, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49,
	0x0a, 0x12, 0x45, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x49, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x5b, 0x0a, 0x13, 0x45, 0x6e, 0x64,
	0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x75, 0x74,
	0x12, 0x25, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x53, 0x65, 0x74, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x65, 0x72, 0x61, 0x69, 0x73, 0x6f, 0x6e, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_endorsement_query_proto_rawDescOnce sync.Once
	file_endorsement_query_proto_rawDescData = file_endorsement_query_proto_rawDesc
)

func file_endorsement_query_proto_rawDescGZIP() []byte {
	file_endorsement_query_proto_rawDescOnce.Do(func() {
		file_endorsement_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_endorsement_query_proto_rawDescData)
	})
	return file_endorsement_query_proto_rawDescData
}

var file_endorsement_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endorsement_query_proto_goTypes = []interface{}{
	(*EndorsementQueryIn)(nil),  // 0: proto.EndorsementQueryIn
	(*EndorsementQueryOut)(nil), // 1: proto.EndorsementQueryOut
	(*Status)(nil),              // 2: proto.Status
}
var file_endorsement_query_proto_depIdxs = []int32{
	2, // 0: proto.EndorsementQueryOut.status:type_name -> proto.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_endorsement_query_proto_init() }
func file_endorsement_query_proto_init() {
	if File_endorsement_query_proto != nil {
		return
	}
	file_status_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_endorsement_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndorsementQueryIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endorsement_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndorsementQueryOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_endorsement_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endorsement_query_proto_goTypes,
		DependencyIndexes: file_endorsement_query_proto_depIdxs,
		MessageInfos:      file_endorsement_query_proto_msgTypes,
	}.Build()
	File_endorsement_query_proto = out.File
	file_endorsement_query_proto_rawDesc = nil
	file_endorsement_query_proto_goTypes = nil
	file_endorsement_query_proto_depIdxs = nil
}
