// Copyright 2026 Contributors to the Veraison project.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: endorsement_store.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEndorsementsArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Environment  []byte `protobuf:"bytes,1,opt,name=environment,json=environment-map,proto3" json:"environment,omitempty"`
	Label        string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	MatchExactly bool   `protobuf:"varint,3,opt,name=match_exactly,json=match-exactly,proto3" json:"match_exactly,omitempty"`
}

func (x *GetEndorsementsArgs) Reset() {
	*x = GetEndorsementsArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endorsement_store_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEndorsementsArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndorsementsArgs) ProtoMessage() {}

func (x *GetEndorsementsArgs) ProtoReflect() protoreflect.Message {
	mi := &file_endorsement_store_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndorsementsArgs.ProtoReflect.Descriptor instead.
func (*GetEndorsementsArgs) Descriptor() ([]byte, []int) {
	return file_endorsement_store_proto_rawDescGZIP(), []int{0}
}

func (x *GetEndorsementsArgs) GetEnvironment() []byte {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *GetEndorsementsArgs) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *GetEndorsementsArgs) GetMatchExactly() bool {
	if x != nil {
		return x.MatchExactly
	}
	return false
}

type SubmitEndorsementsArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endorsement []byte `protobuf:"bytes,1,opt,name=endorsement,json=endorsements,proto3" json:"endorsement,omitempty"`
	Label       string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Activate    bool   `protobuf:"varint,3,opt,name=activate,proto3" json:"activate,omitempty"`
}

func (x *SubmitEndorsementsArgs) Reset() {
	*x = SubmitEndorsementsArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endorsement_store_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitEndorsementsArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitEndorsementsArgs) ProtoMessage() {}

func (x *SubmitEndorsementsArgs) ProtoReflect() protoreflect.Message {
	mi := &file_endorsement_store_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitEndorsementsArgs.ProtoReflect.Descriptor instead.
func (*SubmitEndorsementsArgs) Descriptor() ([]byte, []int) {
	return file_endorsement_store_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitEndorsementsArgs) GetEndorsement() []byte {
	if x != nil {
		return x.Endorsement
	}
	return nil
}

func (x *SubmitEndorsementsArgs) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SubmitEndorsementsArgs) GetActivate() bool {
	if x != nil {
		return x.Activate
	}
	return false
}

var File_endorsement_store_proto protoreflect.FileDescriptor

var file_endorsement_store_proto_rawDesc = []byte{
	0x0a, 0x17, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x77, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x41, 0x72, 0x67, 0x73, 0x12, 0x24, 0x0a, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72,
	0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x65, 0x6e,
	0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x6d, 0x61, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x65, 0x78, 0x61,
	0x63, 0x74, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x2d, 0x65, 0x78, 0x61, 0x63, 0x74, 0x6c, 0x79, 0x22, 0x6d, 0x0a, 0x16, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x45, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x41,
	0x72, 0x67, 0x73, 0x12, 0x21, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x65, 0x72, 0x61, 0x69, 0x73, 0x6f, 0x6e, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_endorsement_store_proto_rawDescOnce sync.Once
	file_endorsement_store_proto_rawDescData = file_endorsement_store_proto_rawDesc
)

func file_endorsement_store_proto_rawDescGZIP() []byte {
	file_endorsement_store_proto_rawDescOnce.Do(func() {
		file_endorsement_store_proto_rawDescData = protoimpl.X.CompressGZIP(file_endorsement_store_proto_rawDescData)
	})
	return file_endorsement_store_proto_rawDescData
}

var file_endorsement_store_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endorsement_store_proto_goTypes = []interface{}{
	(*GetEndorsementsArgs)(nil),    // 0: proto.GetEndorsementsArgs
	(*SubmitEndorsementsArgs)(nil), // 1: proto.SubmitEndorsementsArgs
}
var file_endorsement_store_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_endorsement_store_proto_init() }
func file_endorsement_store_proto_init() {
	if File_endorsement_store_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_endorsement_store_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEndorsementsArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endorsement_store_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitEndorsementsArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_endorsement_store_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endorsement_store_proto_goTypes,
		DependencyIndexes: file_endorsement_store_proto_depIdxs,
		MessageInfos:      file_endorsement_store_proto_msgTypes,
	}.Build()
	File_endorsement_store_proto = out.File
	file_endorsement_store_proto_rawDesc = nil
	file_endorsement_store_proto_goTypes = nil
	file_endorsement_store_proto_depIdxs = nil
}
