# Copyright 2021 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

PROTOSRCS := result.proto
PROTOSRCS += attestation_format.proto
PROTOSRCS += param.proto
PROTOSRCS += token.proto
PROTOSRCS += evidence.proto
PROTOSRCS += attestation.proto
PROTOSRCS += vts.proto

lint lint-extra clean test:

include ../mk/common.mk
include ../mk/proto.mk
