// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: scheme.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReferenceValueIDsArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrustAnchors []byte `protobuf:"bytes,1,opt,name=trust_anchors,json=trust-anchors,proto3" json:"trust_anchors,omitempty"`
	Claims       []byte `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
}

func (x *GetReferenceValueIDsArgs) Reset() {
	*x = GetReferenceValueIDsArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheme_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReferenceValueIDsArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferenceValueIDsArgs) ProtoMessage() {}

func (x *GetReferenceValueIDsArgs) ProtoReflect() protoreflect.Message {
	mi := &file_scheme_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferenceValueIDsArgs.ProtoReflect.Descriptor instead.
func (*GetReferenceValueIDsArgs) Descriptor() ([]byte, []int) {
	return file_scheme_proto_rawDescGZIP(), []int{0}
}

func (x *GetReferenceValueIDsArgs) GetTrustAnchors() []byte {
	if x != nil {
		return x.TrustAnchors
	}
	return nil
}

func (x *GetReferenceValueIDsArgs) GetClaims() []byte {
	if x != nil {
		return x.Claims
	}
	return nil
}

type ValidateEvidenceIntegrityArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Evidence     *AttestationToken `protobuf:"bytes,1,opt,name=evidence,proto3" json:"evidence,omitempty"`
	TrustAnchors []byte            `protobuf:"bytes,2,opt,name=trust_anchors,json=trust-anchors,proto3" json:"trust_anchors,omitempty"`
	Endorsements []byte            `protobuf:"bytes,3,opt,name=endorsements,proto3" json:"endorsements,omitempty"`
}

func (x *ValidateEvidenceIntegrityArgs) Reset() {
	*x = ValidateEvidenceIntegrityArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheme_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateEvidenceIntegrityArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateEvidenceIntegrityArgs) ProtoMessage() {}

func (x *ValidateEvidenceIntegrityArgs) ProtoReflect() protoreflect.Message {
	mi := &file_scheme_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateEvidenceIntegrityArgs.ProtoReflect.Descriptor instead.
func (*ValidateEvidenceIntegrityArgs) Descriptor() ([]byte, []int) {
	return file_scheme_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateEvidenceIntegrityArgs) GetEvidence() *AttestationToken {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *ValidateEvidenceIntegrityArgs) GetTrustAnchors() []byte {
	if x != nil {
		return x.TrustAnchors
	}
	return nil
}

func (x *ValidateEvidenceIntegrityArgs) GetEndorsements() []byte {
	if x != nil {
		return x.Endorsements
	}
	return nil
}

type ExtractClaimsArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Evidence     *AttestationToken `protobuf:"bytes,1,opt,name=evidence,proto3" json:"evidence,omitempty"`
	TrustAnchors []byte            `protobuf:"bytes,2,opt,name=trust_anchors,json=trust-anchors,proto3" json:"trust_anchors,omitempty"`
}

func (x *ExtractClaimsArgs) Reset() {
	*x = ExtractClaimsArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheme_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtractClaimsArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractClaimsArgs) ProtoMessage() {}

func (x *ExtractClaimsArgs) ProtoReflect() protoreflect.Message {
	mi := &file_scheme_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractClaimsArgs.ProtoReflect.Descriptor instead.
func (*ExtractClaimsArgs) Descriptor() ([]byte, []int) {
	return file_scheme_proto_rawDescGZIP(), []int{2}
}

func (x *ExtractClaimsArgs) GetEvidence() *AttestationToken {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *ExtractClaimsArgs) GetTrustAnchors() []byte {
	if x != nil {
		return x.TrustAnchors
	}
	return nil
}

type AppraiseClaimsArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Claims       []byte `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	Endorsements []byte `protobuf:"bytes,2,opt,name=endorsements,proto3" json:"endorsements,omitempty"`
}

func (x *AppraiseClaimsArgs) Reset() {
	*x = AppraiseClaimsArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheme_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppraiseClaimsArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppraiseClaimsArgs) ProtoMessage() {}

func (x *AppraiseClaimsArgs) ProtoReflect() protoreflect.Message {
	mi := &file_scheme_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppraiseClaimsArgs.ProtoReflect.Descriptor instead.
func (*AppraiseClaimsArgs) Descriptor() ([]byte, []int) {
	return file_scheme_proto_rawDescGZIP(), []int{3}
}

func (x *AppraiseClaimsArgs) GetClaims() []byte {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *AppraiseClaimsArgs) GetEndorsements() []byte {
	if x != nil {
		return x.Endorsements
	}
	return nil
}

var File_scheme_proto protoreflect.FileDescriptor

var file_scheme_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x58, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x49, 0x44, 0x73, 0x41, 0x72, 0x67, 0x73, 0x12, 0x24, 0x0a, 0x0d,
	0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0d, 0x74, 0x72, 0x75, 0x73, 0x74, 0x2d, 0x61, 0x6e, 0x63, 0x68, 0x6f,
	0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x22, 0x9e, 0x01, 0x0a, 0x1d, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x49,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x69, 0x74, 0x79, 0x41, 0x72, 0x67, 0x73, 0x12, 0x33, 0x0a, 0x08,
	0x65, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x08, 0x65, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63,
	0x65, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x61, 0x6e, 0x63, 0x68, 0x6f,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x74, 0x72, 0x75, 0x73, 0x74, 0x2d,
	0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x6e, 0x64, 0x6f, 0x72,
	0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x65,
	0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x6e, 0x0a, 0x11, 0x45,
	0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x33, 0x0a, 0x08, 0x65, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x74, 0x74, 0x65, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x08, 0x65, 0x76, 0x69,
	0x64, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x61,
	0x6e, 0x63, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x74, 0x72,
	0x75, 0x73, 0x74, 0x2d, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x73, 0x22, 0x50, 0x0a, 0x12, 0x41,
	0x70, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x41, 0x72, 0x67,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x6e, 0x64,
	0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0c, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x24, 0x5a,
	0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x65, 0x72, 0x61,
	0x69, 0x73, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scheme_proto_rawDescOnce sync.Once
	file_scheme_proto_rawDescData = file_scheme_proto_rawDesc
)

func file_scheme_proto_rawDescGZIP() []byte {
	file_scheme_proto_rawDescOnce.Do(func() {
		file_scheme_proto_rawDescData = protoimpl.X.CompressGZIP(file_scheme_proto_rawDescData)
	})
	return file_scheme_proto_rawDescData
}

var file_scheme_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_scheme_proto_goTypes = []interface{}{
	(*GetReferenceValueIDsArgs)(nil),      // 0: proto.GetReferenceValueIDsArgs
	(*ValidateEvidenceIntegrityArgs)(nil), // 1: proto.ValidateEvidenceIntegrityArgs
	(*ExtractClaimsArgs)(nil),             // 2: proto.ExtractClaimsArgs
	(*AppraiseClaimsArgs)(nil),            // 3: proto.AppraiseClaimsArgs
	(*AttestationToken)(nil),              // 4: proto.AttestationToken
}
var file_scheme_proto_depIdxs = []int32{
	4, // 0: proto.ValidateEvidenceIntegrityArgs.evidence:type_name -> proto.AttestationToken
	4, // 1: proto.ExtractClaimsArgs.evidence:type_name -> proto.AttestationToken
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_scheme_proto_init() }
func file_scheme_proto_init() {
	if File_scheme_proto != nil {
		return
	}
	file_token_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_scheme_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReferenceValueIDsArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scheme_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateEvidenceIntegrityArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scheme_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtractClaimsArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scheme_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppraiseClaimsArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scheme_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scheme_proto_goTypes,
		DependencyIndexes: file_scheme_proto_depIdxs,
		MessageInfos:      file_scheme_proto_msgTypes,
	}.Build()
	File_scheme_proto = out.File
	file_scheme_proto_rawDesc = nil
	file_scheme_proto_goTypes = nil
	file_scheme_proto_depIdxs = nil
}
