// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: vts.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VTSClient is the client API for VTS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VTSClient interface {
	// Return the summary state of the service.
	GetServiceState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceState, error)
	// Returns attestation information -- evidences, endorsed claims, trust
	// vector, etc -- for the provided attestation token data.
	GetAttestation(ctx context.Context, in *AttestationToken, opts ...grpc.CallOption) (*AppraisalContext, error)
	GetSupportedVerificationMediaTypes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MediaTypeList, error)
	GetSupportedProvisioningMediaTypes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MediaTypeList, error)
	SubmitEndorsements(ctx context.Context, in *SubmitEndorsementsRequest, opts ...grpc.CallOption) (*SubmitEndorsementsResponse, error)
	// Returns the public key used to sign evidence.
	GetEARSigningPublicKey(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PublicKey, error)
	// endorsement distribution API
	GetEndorsements(ctx context.Context, in *EndorsementQueryIn, opts ...grpc.CallOption) (*EndorsementQueryOut, error)
}

type vTSClient struct {
	cc grpc.ClientConnInterface
}

func NewVTSClient(cc grpc.ClientConnInterface) VTSClient {
	return &vTSClient{cc}
}

func (c *vTSClient) GetServiceState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceState, error) {
	out := new(ServiceState)
	err := c.cc.Invoke(ctx, "/proto.VTS/GetServiceState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTSClient) GetAttestation(ctx context.Context, in *AttestationToken, opts ...grpc.CallOption) (*AppraisalContext, error) {
	out := new(AppraisalContext)
	err := c.cc.Invoke(ctx, "/proto.VTS/GetAttestation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTSClient) GetSupportedVerificationMediaTypes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MediaTypeList, error) {
	out := new(MediaTypeList)
	err := c.cc.Invoke(ctx, "/proto.VTS/GetSupportedVerificationMediaTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTSClient) GetSupportedProvisioningMediaTypes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MediaTypeList, error) {
	out := new(MediaTypeList)
	err := c.cc.Invoke(ctx, "/proto.VTS/GetSupportedProvisioningMediaTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTSClient) SubmitEndorsements(ctx context.Context, in *SubmitEndorsementsRequest, opts ...grpc.CallOption) (*SubmitEndorsementsResponse, error) {
	out := new(SubmitEndorsementsResponse)
	err := c.cc.Invoke(ctx, "/proto.VTS/SubmitEndorsements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTSClient) GetEARSigningPublicKey(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PublicKey, error) {
	out := new(PublicKey)
	err := c.cc.Invoke(ctx, "/proto.VTS/GetEARSigningPublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTSClient) GetEndorsements(ctx context.Context, in *EndorsementQueryIn, opts ...grpc.CallOption) (*EndorsementQueryOut, error) {
	out := new(EndorsementQueryOut)
	err := c.cc.Invoke(ctx, "/proto.VTS/GetEndorsements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VTSServer is the server API for VTS service.
// All implementations must embed UnimplementedVTSServer
// for forward compatibility
type VTSServer interface {
	// Return the summary state of the service.
	GetServiceState(context.Context, *emptypb.Empty) (*ServiceState, error)
	// Returns attestation information -- evidences, endorsed claims, trust
	// vector, etc -- for the provided attestation token data.
	GetAttestation(context.Context, *AttestationToken) (*AppraisalContext, error)
	GetSupportedVerificationMediaTypes(context.Context, *emptypb.Empty) (*MediaTypeList, error)
	GetSupportedProvisioningMediaTypes(context.Context, *emptypb.Empty) (*MediaTypeList, error)
	SubmitEndorsements(context.Context, *SubmitEndorsementsRequest) (*SubmitEndorsementsResponse, error)
	// Returns the public key used to sign evidence.
	GetEARSigningPublicKey(context.Context, *emptypb.Empty) (*PublicKey, error)
	// endorsement distribution API
	GetEndorsements(context.Context, *EndorsementQueryIn) (*EndorsementQueryOut, error)
	mustEmbedUnimplementedVTSServer()
}

// UnimplementedVTSServer must be embedded to have forward compatible implementations.
type UnimplementedVTSServer struct {
}

func (UnimplementedVTSServer) GetServiceState(context.Context, *emptypb.Empty) (*ServiceState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceState not implemented")
}
func (UnimplementedVTSServer) GetAttestation(context.Context, *AttestationToken) (*AppraisalContext, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttestation not implemented")
}
func (UnimplementedVTSServer) GetSupportedVerificationMediaTypes(context.Context, *emptypb.Empty) (*MediaTypeList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupportedVerificationMediaTypes not implemented")
}
func (UnimplementedVTSServer) GetSupportedProvisioningMediaTypes(context.Context, *emptypb.Empty) (*MediaTypeList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupportedProvisioningMediaTypes not implemented")
}
func (UnimplementedVTSServer) SubmitEndorsements(context.Context, *SubmitEndorsementsRequest) (*SubmitEndorsementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitEndorsements not implemented")
}
func (UnimplementedVTSServer) GetEARSigningPublicKey(context.Context, *emptypb.Empty) (*PublicKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEARSigningPublicKey not implemented")
}
func (UnimplementedVTSServer) GetEndorsements(context.Context, *EndorsementQueryIn) (*EndorsementQueryOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEndorsements not implemented")
}
func (UnimplementedVTSServer) mustEmbedUnimplementedVTSServer() {}

// UnsafeVTSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VTSServer will
// result in compilation errors.
type UnsafeVTSServer interface {
	mustEmbedUnimplementedVTSServer()
}

func RegisterVTSServer(s grpc.ServiceRegistrar, srv VTSServer) {
	s.RegisterService(&VTS_ServiceDesc, srv)
}

func _VTS_GetServiceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTSServer).GetServiceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VTS/GetServiceState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTSServer).GetServiceState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTS_GetAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestationToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTSServer).GetAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VTS/GetAttestation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTSServer).GetAttestation(ctx, req.(*AttestationToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTS_GetSupportedVerificationMediaTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTSServer).GetSupportedVerificationMediaTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VTS/GetSupportedVerificationMediaTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTSServer).GetSupportedVerificationMediaTypes(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTS_GetSupportedProvisioningMediaTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTSServer).GetSupportedProvisioningMediaTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VTS/GetSupportedProvisioningMediaTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTSServer).GetSupportedProvisioningMediaTypes(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTS_SubmitEndorsements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitEndorsementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTSServer).SubmitEndorsements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VTS/SubmitEndorsements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTSServer).SubmitEndorsements(ctx, req.(*SubmitEndorsementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTS_GetEARSigningPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTSServer).GetEARSigningPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VTS/GetEARSigningPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTSServer).GetEARSigningPublicKey(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTS_GetEndorsements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndorsementQueryIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTSServer).GetEndorsements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VTS/GetEndorsements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTSServer).GetEndorsements(ctx, req.(*EndorsementQueryIn))
	}
	return interceptor(ctx, in, info, handler)
}

// VTS_ServiceDesc is the grpc.ServiceDesc for VTS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VTS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.VTS",
	HandlerType: (*VTSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceState",
			Handler:    _VTS_GetServiceState_Handler,
		},
		{
			MethodName: "GetAttestation",
			Handler:    _VTS_GetAttestation_Handler,
		},
		{
			MethodName: "GetSupportedVerificationMediaTypes",
			Handler:    _VTS_GetSupportedVerificationMediaTypes_Handler,
		},
		{
			MethodName: "GetSupportedProvisioningMediaTypes",
			Handler:    _VTS_GetSupportedProvisioningMediaTypes_Handler,
		},
		{
			MethodName: "SubmitEndorsements",
			Handler:    _VTS_SubmitEndorsements_Handler,
		},
		{
			MethodName: "GetEARSigningPublicKey",
			Handler:    _VTS_GetEARSigningPublicKey_Handler,
		},
		{
			MethodName: "GetEndorsements",
			Handler:    _VTS_GetEndorsements_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vts.proto",
}
