# Copyright 2021-2022 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

SUBDIR := common
SUBDIR += cca
SUBDIR += riot
SUBDIR += psa-iot
SUBDIR += tpm-enacttrust
SUBDIR += parsec-tpm
SUBDIR += parsec-cca

clean: ; $(RM) -rf ./bin

include ../mk/subdir.mk
