# Copyright 2021-2026 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

SUBDIR += common

SUBDIR += arm-cca
SUBDIR += parsec-cca
SUBDIR += parsec-tpm
SUBDIR += psa-iot
SUBDIR += riot
SUBDIR += sevsnp
SUBDIR += tpm-enacttrust

SUBDIR += amd-kds-coserv
SUBDIR += nvidia-coserv

clean: ; $(RM) -rf ./bin

include ../mk/subdir.mk
