# This config file assumes the service is being run directly from its build
# location and that the stores have need initialized under /tmp/ (this is done
# automatically if run via  ./run-vts script.
plugin:
  backend: go-plugin
  go-plugin-schemes:
    dir: ../../../scheme/bin/
  go-plugin-stores:
    dir: ../../../store-plugin/bin/
po-store:
  backend: sql
  sql:
    driver: sqlite3
    datasource: /tmp/po-store.sql
po-agent:
  backend: opa
vts:
  server-addr: 127.0.0.1:50051
  tls: true
  cert: ../../../deployments/docker/src/certs/vts.crt
  cert-key: ../../../deployments/docker/src/certs/vts.key
  tls-ca-certs:
      - ../../../deployments/docker/src/certs/rootCA.crt
  corim-ca-certs:
      - ../../../deployments/docker/src/certs/corimCA.crt
ear-signer:
  alg: ES256
  key: ./skey.jwk
endorsement-store:
  coserv:
    signer:
      alg: ES256
      key: ./skey.jwk
    max-expiry: 5 mins
  active-plugins:
    - corim-store
    # - cca-coserv-broker
  plugin-parameters:
    corim-store:
      dbms: sqlite3
      dsn: file::memory:?cache=shared
      trace-sql: false
    cca-coserv-broker:
    # Config for Remote Coserv Service
    # enable-broker ==> "Enable endorsement broker to call remote coserv service"
    # coserv-url ==> "Remote coserv service URL which follows draft-ietf-rats-coserv-06 IETF draft"
    # client-tls-insecure ==> "Enable insecure TLS, no certificate validation"
    # client-certs ==> "If secure TLS, certs to verify with, each path (inside docker container) separated by comma"
    # client-caching ==> "Enable caching for coserv fetch"
    # unsigned-coserv ==> "If true then only accepts unsigned coserv as reponse from remote service"
      enable-broker: false
      coserv-url: "https://veraison.test.linaro.org:11443"
      client-tls-insecure: true
      client-certs: ""
      client-caching: true
      unsigned-coserv: false
logging:
  level: debug
# Scheme configuration Example
# (note: none of the current schemes expect any configuration)
#scheme:
  #ARM_CCA:
    #foo: bar
