# Copyright 2022 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

integration-tests-up:
	docker compose --env-file=../deployments/docker/default.env --file=docker-compose-integration-tests.yml up -d

integration-tests-down:
	docker compose --env-file=../deployments/docker/default.env --file=docker-compose-integration-tests.yml down