# This config file assumes the service is being run via "debug" command
# from the docker deployment debug shell.
logging:
  level: debug  # valid levels: error, warning, info, debug
provisioning:
  listen-addr: 0.0.0.0:8888
  protocol: https
  cert: ../../../deployments/docker/src/certs/provisioning.crt
  cert-key: ../../../deployments/docker/src/certs/provisioning.key
vts:
  server-addr: vts-service:50051
  tls: true
# vim: set ft=yaml:
