.DEFAULT_GOAL := all

CMD := evidence
CMD_DEPS += main.go

include ../../../../../../mk/common.mk
include ../../../../../../mk/cmd.mk
include ../../../../../../mk/lint.mk
include ../../../../../../mk/pkg.mk
