name: coverage

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  cover:
    uses: veraison/ci/.github/workflows/go.yml@main
    with:
      jobs: 'cover'
      install-protoc: true
      check-tests: false # we intentionally exclude some parts
      setup: |
        .github/actions/install-nvat-dev/install.sh
        go install github.com/golang/mock/mockgen@v1.7.0-rc.1
        go install golang.org/x/tools/gopls@latest
        go install golang.org/x/tools/cmd/guru@latest
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
        go install github.com/mitchellh/protoc-gen-go-json@v1.1.0
      cover-command: 'make coverage CI_PIPELINE=true'
      check-coverage: false # already done by the command itself