# End to end integration tests - GitHub Actions
name: integration tests
on: [push, pull_request]
jobs:
  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Veraison deployment
      run: make docker-deploy
    - name: Run integration tests
      run: make integ-test | tee tavern-tests.log
    - name: Archive tavern container log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: tavern-logs
        path: ./tavern-tests.log
    - name: Check for failures
      run: grep 'FAILURES' tavern-tests.log | python3 scripts/integ-fail.py
    - name: Save docker compose logs
      if: always()
      run: deployments/docker/veraison get-logs container-logs
    - name: Archive container logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: container-logs
        path: ./container-logs
    - name: Tear down services
      run: deployments/docker/veraison stop
