// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: decoder_response.proto

package decoder

import (
	proto "github.com/veraison/services/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndorsementDecoderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SwComponents []*proto.Endorsement `protobuf:"bytes,1,rep,name=swComponents,proto3" json:"swComponents,omitempty"`
	TrustAnchors []*proto.Endorsement `protobuf:"bytes,2,rep,name=trustAnchors,proto3" json:"trustAnchors,omitempty"`
}

func (x *EndorsementDecoderResponse) Reset() {
	*x = EndorsementDecoderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_decoder_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndorsementDecoderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndorsementDecoderResponse) ProtoMessage() {}

func (x *EndorsementDecoderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_decoder_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndorsementDecoderResponse.ProtoReflect.Descriptor instead.
func (*EndorsementDecoderResponse) Descriptor() ([]byte, []int) {
	return file_decoder_response_proto_rawDescGZIP(), []int{0}
}

func (x *EndorsementDecoderResponse) GetSwComponents() []*proto.Endorsement {
	if x != nil {
		return x.SwComponents
	}
	return nil
}

func (x *EndorsementDecoderResponse) GetTrustAnchors() []*proto.Endorsement {
	if x != nil {
		return x.TrustAnchors
	}
	return nil
}

var File_decoder_response_proto protoreflect.FileDescriptor

var file_decoder_response_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x09, 0x76, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x1a, 0x45, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x36, 0x0a, 0x0c, 0x73, 0x77, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0c, 0x73, 0x77, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x36, 0x0a, 0x0c, 0x74, 0x72, 0x75, 0x73,
	0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x0c, 0x74, 0x72, 0x75, 0x73, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x73,
	0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76,
	0x65, 0x72, 0x61, 0x69, 0x73, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x2f, 0x64, 0x65,
	0x63, 0x6f, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_decoder_response_proto_rawDescOnce sync.Once
	file_decoder_response_proto_rawDescData = file_decoder_response_proto_rawDesc
)

func file_decoder_response_proto_rawDescGZIP() []byte {
	file_decoder_response_proto_rawDescOnce.Do(func() {
		file_decoder_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_decoder_response_proto_rawDescData)
	})
	return file_decoder_response_proto_rawDescData
}

var file_decoder_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_decoder_response_proto_goTypes = []interface{}{
	(*EndorsementDecoderResponse)(nil), // 0: endorsement_decoder_response.EndorsementDecoderResponse
	(*proto.Endorsement)(nil),          // 1: proto.Endorsement
}
var file_decoder_response_proto_depIdxs = []int32{
	1, // 0: endorsement_decoder_response.EndorsementDecoderResponse.swComponents:type_name -> proto.Endorsement
	1, // 1: endorsement_decoder_response.EndorsementDecoderResponse.trustAnchors:type_name -> proto.Endorsement
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_decoder_response_proto_init() }
func file_decoder_response_proto_init() {
	if File_decoder_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_decoder_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndorsementDecoderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_decoder_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_decoder_response_proto_goTypes,
		DependencyIndexes: file_decoder_response_proto_depIdxs,
		MessageInfos:      file_decoder_response_proto_msgTypes,
	}.Build()
	File_decoder_response_proto = out.File
	file_decoder_response_proto_rawDesc = nil
	file_decoder_response_proto_goTypes = nil
	file_decoder_response_proto_depIdxs = nil
}
